version: '3'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    networks: 
      - production-network
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: teravoz
      MYSQL_DATABASE: teravoz
      MYSQL_USER: root
      MYSQL_PASSWORD: teravoz

  teravoz:
    build:
      dockerfile: ./docker/teravoz.dockerfile
      context: .
    image: leonardo/teravoz
    container_name: teravoz
    ports:
      - "3001"
    networks: 
      - production-network
    depends_on:
      - "mysql"
  
  client:
    build:
      dockerfile: ./docker/client.dockerfile
      context: .
    image: leonardo/teravoz
    container_name: teravoz
    ports:
      - "3000"
    networks: 
      - production-network
    depends_on:
      - "teravoz"
  
  
networks: 
  production-network:
    driver: bridge
